# Generated by Django 2.0.3 on 2020-05-23 02:26

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('fonctionnements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='infobule',
            name='contenu',
            field=mdeditor.fields.MDTextField(default=''),
            preserve_default=False,
        ),
    ]
