# Generated by Django 2.0.3 on 2020-05-23 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fonctionnements', '0002_infobule_contenu'),
    ]

    operations = [
        migrations.AddField(
            model_name='infobule',
            name='slug',
            field=models.SlugField(blank=True, max_length=1000),
        ),
    ]
