# Generated by Django 2.0.3 on 2020-05-23 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fonctionnements', '0003_infobule_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='infobule',
            options={'ordering': ['-created', '-updated']},
        ),
    ]
