# Generated by Django 2.0.3 on 2020-05-24 23:07

from django.db import migrations, models
import saintexupery.utils


class Migration(migrations.Migration):

    dependencies = [
        ('fonctionnements', '0005_calendrier_horaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendrier',
            name='doc_pdf',
            field=models.FileField(blank=True, null=True, upload_to=saintexupery.utils.upload_file_location),
        ),
        migrations.AddField(
            model_name='horaire',
            name='doc_pdf',
            field=models.FileField(blank=True, null=True, upload_to=saintexupery.utils.upload_file_location),
        ),
    ]
