# Generated by Django 2.0.3 on 2020-05-25 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fonctionnements', '0006_auto_20200524_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horaire',
            name='titre',
            field=models.CharField(default='Horaire', max_length=255),
        ),
    ]
