# Generated by Django 2.0.3 on 2020-03-19 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20200316_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='telephone',
        ),
    ]
