# Generated by Django 2.0.3 on 2020-05-23 07:23

import cycles.models
from django.db import migrations, models
import mdeditor.fields
import saintexupery.utils



class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('type_cycle', models.CharField(choices=[('prsentation', 'Présentation des cycles'), ('cycle', 'Un cycle')], default='cycle', max_length=255)),
                ('classes', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('image', models.FileField(upload_to=saintexupery.utils.upload_file_location)),
                ('description', mdeditor.fields.MDTextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created', '-updated'],
            },
        ),
    ]
