# Generated by Django 2.0.3 on 2020-05-23 08:09

import cycles.models
from django.db import migrations, models
import mdeditor.fields
import saintexupery.utils



class Migration(migrations.Migration):

    dependencies = [
        ('cycles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(default='Présentation des cycles du centre', max_length=255)),
                ('slug', models.SlugField()),
                ('image', models.FileField(upload_to=saintexupery.utils.upload_file_location)),
                ('description', mdeditor.fields.MDTextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Présention des cycles',
                'verbose_name_plural': 'Présentations des cycles',
            },
        ),
        migrations.AlterModelOptions(
            name='cycle',
            options={'ordering': ['-created', '-updated'], 'verbose_name': 'Cycle', 'verbose_name_plural': 'Les cycles'},
        ),
    ]
