# Generated by Django 2.0.3 on 2020-05-23 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycles', '0003_remove_cycle_type_cycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='cycle',
            name='niveau_cycle',
            field=models.CharField(choices=[('primaire', 'primaire'), ('college', 'Collège'), ('lycee', 'Lycée')], default='primaire', max_length=255),
            preserve_default=False,
        ),
    ]
