# Generated by Django 2.0.3 on 2020-05-26 17:38

from django.db import migrations, models
import django.utils.timezone
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(default="Information sur l'inscription", max_length=250)),
                ('description', mdeditor.fields.MDTextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='inscription',
            name='date_inscription',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inscription',
            name='date_modification_inscription',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='date_naissance',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='niveau',
            field=models.CharField(choices=[('Grande section maternelle primaire', (('ce1', 'CP ou CE1'), ('ce2', 'CE1  ou CE2'), ('ce3', 'CE2  ou CE3'), ('ce4', 'CM1 ou CE4'), ('ce5', 'CM2 ou CE5'))), ('Collège', (('ce6', '6ème ou CE6'), ('ce7', '5ème ou CE7'), ('ce8', '4ème CE8'), ('ce9', '3ème ou CE9'))), ('Lycée', (('deuxieme', '2de ou tronc commun'), ('premiere_generale', '1ère générale ou 1ère lycée'), ('premiere_stmg', '1ère STMG ou 2ème année lycée'), ('terminale_generale', 'Terminale Générale'), ('terminale_stmg', 'Terminale STMG')))], max_length=250),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='representant_parent_deux',
            field=models.CharField(choices=[('pere', 'Mère'), ('mere', 'Personne morale ')], max_length=250),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='representant_parent_un',
            field=models.CharField(choices=[('pere', 'Père'), ('mere', 'Personne morale ')], max_length=250),
        ),
    ]
