# Generated by Django 2.0.3 on 2020-04-30 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0002_auto_20200430_0342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='date_naissance_parent_deux',
            field=models.CharField(max_length=250),
        ),
    ]
