# Generated by Django 2.0.3 on 2020-05-22 17:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0006_auto_20200430_0707'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='date_inscription',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inscription',
            name='date_modification_inscription',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
