# Generated by Django 2.0.3 on 2019-10-01 13:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import evenements.models
import saintexupery.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('image', models.FileField(upload_to=saintexupery.utils.upload_file_location)),
                ('content', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created', '-updated'],
            },
        ),
        migrations.CreateModel(
            name='ArticleMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photos', models.FileField(upload_to=saintexupery.utils.upload_file_location)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evenements.Article')),
            ],
        ),
    ]
