# Generated by Django 2.0.3 on 2019-04-13 01:53

from django.db import migrations, models
import evenements.models


class Migration(migrations.Migration):

    dependencies = [
        ('evenements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.FileField(upload_to=evenements.models.upload_file_location),
        ),
        migrations.AlterField(
            model_name='articlemedia',
            name='photos',
            field=models.FileField(upload_to=evenements.models.upload_file_location),
        ),
    ]
