# Generated by Django 2.0.3 on 2020-05-22 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evenements', '0002_article_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
