# Generated by Django 2.0.3 on 2020-05-22 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evenements', '0003_article_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='active',
            new_name='permettre',
        ),
    ]
