# Generated by Django 2.0.3 on 2020-05-26 05:42

from django.db import migrations, models
import saintexupery.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250)),
                ('prenom', models.CharField(max_length=250)),
                ('civilite', models.CharField(choices=[('Mr', 'Mr'), ('Mme', 'Mme'), ('Melle', 'Melle')], max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=33)),
                ('cv', models.FileField(upload_to=saintexupery.utils.upload_file_location)),
                ('poste', models.CharField(max_length=250)),
                ('message', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'La Candidature',
                'verbose_name_plural': 'Les Candidatures',
            },
        ),
    ]
