# Generated by Django 2.0.3 on 2019-04-13 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generale',
            options={'verbose_name': "L'Ecole", 'verbose_name_plural': "L'Ecole"},
        ),
        migrations.AddField(
            model_name='generale',
            name='presentation_type',
            field=models.CharField(blank=True, choices=[('presentation', 'Présentation'), ('mot_directrice', 'Mot du directeur'), ('programme', 'Programe du CNED'), ('equipe_pedagogique', 'Equipe pédagogique')], max_length=250, null=True),
        ),
    ]
