# Generated by Django 2.0.3 on 2019-04-13 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentation', '0002_auto_20190413_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generale',
            name='presentation_type',
            field=models.CharField(choices=[('presentation', 'Présentation'), ('mot_directrice', 'Mot du directeur'), ('programme', 'Programe du CNED'), ('equipe_pedagogique', 'Equipe pédagogique')], max_length=250),
        ),
    ]
