# Generated by Django 2.0.3 on 2019-04-13 01:53

from django.db import migrations, models
import presentation.models


class Migration(migrations.Migration):

    dependencies = [
        ('presentation', '0003_auto_20190413_0028'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partenaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250)),
                ('slug', models.SlugField()),
                ('contenu', models.TextField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to=presentation.models.upload_file_location)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='generale',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=presentation.models.upload_file_location),
        ),
    ]
