# Generated by Django 2.0.3 on 2020-05-23 05:28

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('presentation', '0003_generale_capsule_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partenaire',
            old_name='title',
            new_name='nom',
        ),
        migrations.AlterField(
            model_name='generale',
            name='content',
            field=mdeditor.fields.MDTextField(),
        ),
        migrations.AlterField(
            model_name='partenaire',
            name='contenu',
            field=mdeditor.fields.MDTextField(),
        ),
    ]
