# Generated by Django 2.0.3 on 2020-05-23 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentation', '0004_auto_20200523_0528'),
    ]

    operations = [
        migrations.AddField(
            model_name='partenaire',
            name='lien_site',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
