# Generated by Django 2.0.3 on 2019-04-13 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presentation', '0004_auto_20190413_0153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partenaire',
            old_name='nom',
            new_name='title',
        ),
    ]
