# Generated by Django 2.0.3 on 2020-05-25 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presentation', '0006_equipepedagogique'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EquipePedagogique',
        ),
        migrations.AlterModelOptions(
            name='generale',
            options={'verbose_name': 'Le centre', 'verbose_name_plural': 'Le centre'},
        ),
    ]
